PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE {
  FILTER NOT EXISTS {
    ?resource rdf:type owl:Class .
    ?resource rdf:type owl:NamedIndividual .
  }
FILTER(isIRI(?resource))
}
