PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?resource WHERE {
  { ?subject ?resource ?object }
  UNION
  { ?subject ?predicate ?resource }
  FILTER (isIRI(?resource) && STRSTARTS(STR(?resource), "http://www.w3.org/2000/01/rdf-schema#"))
  FILTER NOT EXISTS { ?resource rdf:type ?type }
}

