PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX cco: <https://www.commoncoreontologies.org/>

SELECT DISTINCT ?resource WHERE {
  ?resource rdf:type owl:Ontology ; cco:ont00001744 ?value .
  FILTER (isLiteral(?value) && LANG(?value) = "")
}
